name: Release
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.PERSON_ACCESS_TOKEN_FOR_PUSH_TO_GH_PAGES_BRANCH }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
#      - name: Setup Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: 19
#      - name: Install dependencies
#        run: yarn
#      - name: Pull from Notion
#        env:
#          DOCU_NOTION_INTEGRATION_TOKEN: ${{ secrets.DOCU_NOTION_INTEGRATION_TOKEN }}
#          DOCU_NOTION_SAMPLE_ROOT_PAGE: ${{ secrets.DOCU_NOTION_SAMPLE_ROOT_PAGE }}
#        run: yarn pull
#      - name: Commit
#        uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          commit_message: Apply changes from docu-notion
#      - name: Build github pages branch
#        run: yarn build
#      - name: Deploy to gh-pages
#        env:
#          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
#          BACKEND_API_URL: ${{ secrets.BACKEND_API_URL }}
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.PERSON_ACCESS_TOKEN_FOR_PUSH_TO_GH_PAGES_BRANCH }}
#          publish_dir: ./build
